spring:
  data:
    mongodb:
      uri: mongodb+srv://saucekode:softbadass832@fotosplash.715ur.mongodb.net/test

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 592480365296-2j6kv857friu2jf1vvj7u3rtrmsk8l5v.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

app:
  auth:
    jwtSecret: 04ca023b39512e46d0c2cf4b48d5aac61d33b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    jwtExpirationInMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - https://objective-dubinsky-cb9c46.netlify.app/oauth2/redirect