spring:
  data:
    mongodb:
      uri: ${MONGO_URI}

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

app:
  cors:
    allowedOrigins: ${ALLOWED_ORIGINS}

  auth:
    tokenSecret: ${JWTSECRET}
    tokenExpirationMsec: ${JWTEXPTIME}

  oauth2:
    authorizedRedirectUris: ${ALLOWED_REDIRECTS}